// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmkofvtcchzlrvciwipq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxta29mdnRjY2h6bHJ2Y2l3aXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzA4MTUsImV4cCI6MjA2NTg0NjgxNX0.4uVxO9uWBj1LiXXhXFOdL8bmd-kmatvcaCZ1CxMxVkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);